### PR TITLE
initial commit for multiarch-dockerfiles

### PR DESCRIPTION
**Pull request by CBrosius**
the multi-arch-manifest.yaml has to be modified to match the original dockerhub repo

Signed-off-by: Christian Brosius <Christian.Brosius@gmail.com>

### CODE REVIEW

**Comment by jjethwa** [comment]
Thanks so much, @CBrosius 

Just to be sure, the manifest file should look like:
```
image: jordan/icinga2:latest
manifests:
  - image: jordan/icinga2:latest-amd64
    platform:
      architecture: amd64
      os: linux
  - image: jordan/icinga2:latest-arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: jordan/icinga2:latest-arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
 ```

**Comment by CBrosius** [comment]
yes, and you have to set up a separate dockerhub build-job for them

image

**Comment by jjethwa** [comment]
Thanks so much, @CBrosius 

I'll work on merging later this week.  Really appreciate your PR and continued support

**Review by jjethwa — APPROVED** [review]

**Comment by jjethwa** [comment]
Looks like the images are building but Docker Hub shows build failures with errors such as
```
Starting Manifest-Tool
time="2021-01-13T04:39:28Z" level=fatal msg="Inspect of image \"jordan/icinga2:latest-arm32v7\" failed with error: manifest unknown: manifest unknown"
post_push hook failed! (1)
```

Any idea how to fix that @CBrosius ?

**Comment by CBrosius** [comment]
I`m not sure about that. was it before all build-jobs were done? Because the image-tool is looking for the "sub-builds" to collect a summary icinga2:latest from it.
If you are running this without a latest-arm32v7 available, this may cause this error.

The dockerfile on hub.docker.com switched to the arm64v8 version. Was that intended?

Apart from that, everything looks fine from my perspective.

**Comment by jjethwa** [comment]
Hi @CBrosius 


Sorry for the delayed response, it's been a little hectic the past few weeks.  I think that you were right.  I needed to do another build as maybe part of the multiarch test is done by pulling the previous build.  It seems to be working as far as I can tell as there are pulls for the arm builds.  If you get a chance to confirm, let me know 😄

**Pull request merged**
