### PR TITLE
Support empty volume mapping

### PR DESCRIPTION
**Pull request by lkm**
I thought it would be good to have the option of using volumes and start from scratch, ie without db or config files already inside volumes

### CODE REVIEW

**Comment by jjethwa** [comment]
Hi @lkm 

Thank you so much for this pull request!  Really appreciate all of the work you put into it.  I'm hesitant to add the volumes back into the Dockerfile.  Please see: https://github.com/docker/docker/issues/2259

What do you think?  Thanks again :)

**Comment by lkm** [comment]
Hi @jjethwa, sorry I lost track of this. I see, yes, it would mean that you have to run it as root for this PR to work. It does enable upgrades even if you don't explicitly map the volumes (`--volumes-from`), which you would have to read the Dockerfile in details to get. Mostly I just get a bad feel when containers aren't made to be immutable.

**Comment by jjethwa** [comment]
Hi @lkm 

Thanks!  I'll merge the PR as I really like the changes you've made, but I'll keep the VOLUME line in the Dockerfile commented out.  I'd like to have it back in there myself, but until the aforementioned issue is fixed, adding VOLUME will only cause a lot of pain :(

**Comment by jjethwa** [comment]
@lkm 

Layers cut in half :+1:

**Pull request merged**
