### PR TITLE
Changed initfile location and test file location for pki

### PR DESCRIPTION
**Pull request by Gibby**
This will allow for someone to start up the image without specifying any volumes then with the -v and --volume-from option copy the data down to the host and then start the image again specifying each volume path.

### CODE REVIEW

**Comment by jjethwa** [comment]
Hi @Gibby 

Thanks for the pull request.  I'm on vacation until the end of the month but will look into this as soon as I'm back.  I'll need to perform some testing, etc before merging into master.  Thanks :)

**Comment by jjethwa** [comment]
Hi @Gibby 

I have a concern with the initfile location move.  We need to have the block inside the initfile if statement run the first time when starting a container for the first time. If the initfile exists (from a volume), then that part is skipped so the passwords, etc will not get updated.  I think this issue only arises in the case when a container is started without using a volume but then restarted with a volume later on, right?  In this case, you could just a new container with the volume(s) instead of re-using the old one.  What do you think?

**Comment by Gibby** [comment]
That is what I was going for, not running the init/password part if the init file exists in the volume being mounted. I use this so I can change the docker host with a simple docker run without having the init part run. If you want it to run, it is as simple as removing it. The way it is now there is no way to start it for the first time without init running.

**Comment by jjethwa** [comment]
@Gibby 
Ah, got it, thanks :)   I'm going to merge everything except the nagios-nrpe-plugin addition since it's better to use the distributed monitoring aspect of Icinga2 (more secure, etc).

**Pull request merged**
