### PR TITLE
Support MySQL 8.0

### PR DESCRIPTION
**Pull request by rayyen**
Modify GRANT SQL to support MySQL 8.0 new syntax for create and grant user.

tested environment

version	8.0.15
version_comment	MySQL Community Server - GPL
version_compile_machine	x86_64
version_compile_os	 Linux

### CODE REVIEW

**Comment by rayyen** [comment]
no idea why everything goes fine in my Visual Code but wrong intent on github.

**Comment by rayyen** [comment]
some thing went wrong on K8s with new images and MySQL8.0 image, please pending this request.

**Comment by rayyen** [comment]
problem solved., check mysql user if exists or not. please review, thanks.

**Comment by rayyen** [comment]
will reopen after I test.

**Comment by bebehei** [comment]
Please squash your commits when reopening, too. (`git rebase -i master` and then a force push)

**Comment by rayyen** [comment]
Update: 
Using external MySQL 8.0 or 5.7, icingaweb2 can not retrieve get host or service detail.
Still digging why
image


no problem to work with local MySQL 5.7, 8.0.

- Test Env 
K8s v1.10.1 on Ubuntu 18.04 baremetal

**Comment by gkohler79** [comment]
I'm curious, I'm still a bit new to github, pull request, etc but I don't see this change to ultimately support mysql 8 in the master branch.  Was it rejected?

Thanks,
-Grant

**Comment by bebehei** [comment]
Yes. But actually the [author "rejected" it by himself](https://github.com/jjethwa/icinga2/pull/178#event-2218905238).

I had taken a hiatus on February to May and I don't know why I've commented in March here. But looking at the code again: It's absolutely necessary to create a MySQL user on the DB server and we have to use such a thing.

**Comment by gkohler79** [comment]
I tried to setup a user manually for the 3 databases and omit the MySQL_ROOT_USER envy variable but it still didn’t seem to work. 

I’m going to try again today to see if I missed something. 

It seems to be me if I follow these steps it should work. 

1. Launch the container plain and let the databases create themselves on the localhost. 

2. Dump the databases from localhost and import them to the external database server. 

3. Create users with full access to the databases on the external database and setup those users as well as the connection strings as environment variables. 

4. Kill and relaunch the container. 

In my mind, that should work, right?  Again, omitting the mysql_root_user variable so it doesn’t try and create the databases on the external server.

**Comment by gkohler79** [comment]
Well I tried the process above.  It appears the current code will not allow you to use an external database unless you supply the MYSQL_ROOT_PASSWORD env variable.  

Since the current codebase isn't compatible with Mysql 8.0, and supplying MYSQL_ROOT_PASSWORD makes the software attempt to create the database and add a user, this image won't work without a code update to support MySQL 8.0.  That kind of sucks, because this image is fantastic outside of that!

Any chance an update could be pushed through?

**Comment by rayyen** [comment]
@gkohler79  and @bebehei 

I did not push my code because of following considerations.

1. My changes support external MySQL 8 only. By default, the debian:stretch provides MySQL 5. therefore, the meaning of  "Support MySQL 8", it is better to make the version of MySQL become optional. However, I did not do that.
2. I did not do the full test for MySQL 5. To avoid polluting the source code of this project, I decide reject my own request.

But you can use my image.  I use it on my production env and so far so good.
`docker pull rayyen/icinga-mysql8.0:latest`

**Pull request closed without merging**
