### PR TITLE
Switch install recommends on for icinga packages.

### PR DESCRIPTION
**Pull request by lazzurs**
This will install the recommended packages for the icinga packges.

Doing this to ensure plugins have the perl libs and supporting tools
they need to run.

### CODE REVIEW

**Comment by lazzurs** [comment]
Happy to split this out so it only does an install recommends for the plugins rather than all the icinga packages.

**Comment by bebehei** [comment]
Can you give a better example please or some log output?

I guess this is just a simple dependency problem. Activating the recommends packages blows up the image.

**Comment by lazzurs** [comment]
Ok so given the above example of check_whois 

```root@b7508df34aca:/# /usr/lib/nagios/plugins/check_whois
Can't locate Date/Manip.pm in @INC (you may need to install the Date::Manip module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/lib/nagios/plugins/check_whois line 71.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/check_whois line 71.```

This comes from the package `nagios-plugins-contrib` which has the following as recommends

```Recommends: libsocket-perl, libmonitoring-plugin-perl | libnagios-plugin-perl (>= 0.31), libnet-snmp-perl (>= 5), whois, nagios-plugins-basic, libnet-dns-perl, libdate-manip-perl, libnet-cups-perl, libio-socket-ssl-perl, libmail-imapclient-perl, libnet-smtp-tls-perl, libnet-smtp-ssl-perl, libnet-ssleay-perl, libnet-smtpauth-perl, bind9-host | knot-host, python, liblocale-gettext-perl, liblwp-useragent-determined-perl, snmp, freeipmi-tools, libipc-run-perl, lsof, libyaml-syck-perl, libxml-simple-perl, python-pymongo, libdbd-mysql-perl, libreadonly-perl, libdata-validate-domain-perl, libdata-validate-ip-perl, libredis-perl, libtimedate-perl, openssl, libwebinject-perl, libnet-dns-sec-perl, ruby | ruby-interpreter, binutils, perl:any, libc6 (>= 2.14), libmemcached11, libmemcachedutil2, libvarnishapi1 (>= 3.0.0)```

These are all requirements of the plugins that come with this package.

I think either install recommends of all the icinga packages or at the least install recommends for the plugins packages to ensure all of the plugins in the container will execute.

**Comment by jjethwa** [comment]
Thanks @lazzurs   I think this is a pretty safe change and won't fatten the image up too much since @bebehei already split the icinga2 installs from some of the other base installs.  Really appreciate it!

**Comment by bebehei** [comment]
I've just watched a talk, I had on my watch later list for a long time: [Dockerfile Best Practices](https://youtu.be/JofsaZ3H1qM?t=465). So I just remembered this PR and created some stats:

What should I say? With this PR, the build time grew by ~50% on my system and the final image size got 30% bigger. :confused:  I'd bet there would be a much smarter solution.

**Comment by jjethwa** [comment]
Thanks, @bebehei 

Didn't think it would balloon that badly and didn't have time to check post build.  I think the only way around this would be to find the required packages one by one 😞

**Pull request merged**
