### PR TITLE
Moved configuration files

### PR DESCRIPTION
**Pull request by satreix**

### CODE REVIEW

**Comment by jjethwa** [comment]
Thank you so much, satreix!  Really appreciate the great pull request :)

**Comment by satreix** [comment]
I'm working on an update to your Dockerfile to add [icingaweb2](https://github.com/Icinga/icingaweb2) to it.
It is not yet ready but you can already look up the work (barely adding the source for now) here:

[satreix/icinga2:mine](https://github.com/satreix/icinga2/tree/mine)

I still need to take care of the webapp part of the setup.

**Comment by jjethwa** [comment]
Hi @satreix 

I have a working container but was waiting for the Icinga team to push out the first RC.  I'll see if I can get it done in a few days :)

**Comment by satreix** [comment]
How did you do the WEB part of the setup.

**Comment by jjethwa** [comment]
Hi @satreix 

Right now it requires that you push multiple configuration files as they do not exist until you run the wizard.  I believe this should be simplified when the RCs come out but am not 100% sure.  I don't think it's a good idea for us to maintain the config files since they might change often during the first few major releases of icingaweb2.  Unfortunately I had to do that with the IDO database XML file but luckily that particular file has not changed.  Let me know your thoughts :)

**Comment by satreix** [comment]
Do we have a date for the first RC? For now I'm interested in having a working Dockerfile from 0 to icinga2 + icingaweb2 working. We only need to add the web setup directly to the Dockerfile or _/opt/run_.

The goal here for me is to use that first container as a base for another one I'll use that might add my icinga2 configuration (host & services). For that I need the web setup to be gone.

**Comment by jjethwa** [comment]
Hi @satreix 

I don't know the dates unfortunately.  I know it's running a bit behind schedule.  I met with the team a few months ago and they're working very hard on it :)

**Comment by jjethwa** [comment]
Hi @satreix 

I should be pushing the changes today to enable icingaweb2 (time permitting) :)

Out of curiosity, are you going to use a data only container for your configurations?  I would go with that option or using the included volumes instead of building your own container off this one as it gets you out of having to rebuild your container if this one updates.  Should reduce overhead a little :)

**Comment by jjethwa** [comment]
Hi @satreix 

I've merged the changes to enable icingaweb2 into master

**Comment by satreix** [comment]
> Out of curiosity, are you going to use a data only container for your configurations?

I would also go with that option.

Thanks for the merge, I will look at it in the afternoon and try it to see how it behaves.

**Pull request merged**
