### PR TITLE
move image to debian stretch (WIP)

### LINKED ISSUE #104: Debian Stretch
Debian stretch is out. Let's test it and upgrade!

### PR DESCRIPTION
**Pull request by bebehei**
- [x] lower layer is adapted
- [x] icinga2 package names updated
- [x] icingaweb2 works
- [x] compatible to jessie version

fixes #104 (at the end)

### CODE REVIEW

**Comment by jjethwa** [comment]
Wow, you're already on it!  😄

**Comment by bebehei** [comment]
Well, everything seemed to work fine. Then I started my production container with the image. And it crashed. The switch from mysql to mariadb did not work.

**Comment by jjethwa** [comment]
@bebehei  Did you try running mysql_upgrade?

**Comment by bebehei** [comment]
Well, I found the "problem". All my hosts run on Ubuntu 16.04. So I thought I'd give it a try and use Ubuntu 16.04 as the base image. It worked fine. But after testing it with the "production" container, mysql stopped working there because of some weird InnoDB checksum failures.

I restored my backup and used debian:stretch again and it works fine since then.

**Comment by jjethwa** [comment]
Hi @bebehei 

Got notified of an issue with my Rundeck container and stretch and I believe we'll run into it here as well.  MariaDB on Debian no longer requires the use of the debian-sys-maint user.  It now uses the MariaDB root user so we don't need to touch the debian.cnf

We can remove these lines:

https://github.com/bebehei/icinga2-docker/blob/debian-stretch/content/opt/setup/mysql#L12-L22

**Comment by jjethwa** [comment]
@bebehei  Icinga2 v.2.7.0 has been released.  Do you have time to wrap up this PR or should I work on it? 😄

**Comment by bebehei** [comment]
According to [the release notes](https://www.debian.org/releases/stable/amd64/release-notes/ch-whats-new.en.html#mariadb-replaces-mysql), the mysql upgrade is safe to be done in place.

I added the neccessary stuff. I think we can merge this PR now.

**Pull request merged**
